[skip changelog] Add link check exclusions for broken generated Protocol Buffer doc links (#3221)
Documentation of the Protocol Buffers interface is automatically generated from the project source code.

Unfortunately the documentation generator produces some broken links. These cause the project infrastructure's link
checker to fail:

```
ERROR: 104 dead links found in ./docs/rpc/commands.md !
[✖] #google-protobuf-Any → Status: 404
[✖] #google-rpc-Status → Status: 404
```

It will not be feasible to fix these links, so the only available resolution for those link check failures is to
configure exclusions.