[skip-changelog] Extend code-coverage to integration test (#2103)
* Upgrade minimum go version to 1.20

* Updated license cache

* Implemented code coverage in integration tests

* Use gocovmerge to merge all coverage artifacts

* Fixed build error on macOS dist

The error was due to an increased git security constraints

  ...
  go: downloading github.com/xanzy/ssh-agent v0.2.1
  go: downloading gopkg.in/warnings.v0 v0.1.2
  error obtaining VCS status: exit status 128
	Use -buildvcs=false to disable VCS stamping.
  Error: failed building for darwin/amd64: exit status 1
  failed building for darwin/amd64: exit status 1
  task: Failed to run task "dist:macOS_64bit": exit status 1

To fix this I followed the suggestion here https://github.com/elastic/golang-crossbuild/issues/232

* Before killing the daemon, try a graceful shutdown

Otherwise the process will not outut the coverage data.