Fixed integration test failure:
<<< Run completed (err = <nil>)
    environment.go:52:
        	Error Trace:	D:/a/arduino-cli/arduino-cli/internal/integrationtest/environment.go:52
            			D:/a/arduino-cli/arduino-cli/internal/integrationtest/environment.go:63
        	            	D:/a/arduino-cli/arduino-cli/internal/integrationtest/environment.go:63
        	            	D:/a/arduino-cli/arduino-cli/internal/integrationtest/environment.go:69
        	            	D:/a/arduino-cli/arduino-cli/internal/integrationtest/board/board_test.go:638
        	Error:      	Received unexpected error:
        	            	remove C:\Users\runneradmin\AppData\Local\Temp\cli2634248494\A\inventory.yaml: The process cannot access the file because it is being used by another process.
        	Test:       	TestCLIStartupWithCorruptedInventory
--- FAIL: TestCLIStartupWithCorruptedInventory (8.45s)