[skip changelog] Adjust link exclusions for project's protoc-gen-doc version (#3225)
Documentation of the Protocol Buffers interface is automatically generated from the project source code.

Unfortunately the protoc-gen-doc documentation generator tool produces some broken links. These cause the project
infrastructure's link checker to fail:

```
ERROR: 2 dead links found in ./docs/rpc/commands.md !
[✖] #google.protobuf.Any → Status: 404
[✖] #google.rpc.Status → Status: 404
```

It will not be feasible to fix these links, so the only available resolution for those link check failures is to
configure exclusions.

The previous exclusions were tailored to the links generated by the modern version of protoc-gen-doc. It turns out that
the project infrastructure has an unfortunate design where management of this tool dependency is only done in the GitHub
Actions workflows. This means that when the documentation generation is performed locally by a contributor, a different
version of protoc-gen-doc may be used than that used by the CI system. The outdated version of protoc-gen-doc installed
by the Github Actions workflow generates links with different fragment ID format than the modern version of the tool.
That resulted in exclusions that caused the link check to pass locally, but fail in the CI runs.

The link checker exclusions are hereby updated to match the links generated by the outdated version of protoc-gen-doc
used by the project's GitHub Actions workflows.