On compile command: implemented `--quiet` flag / removed libraries recap on default verbosity level. (#2820)
* Made builder logger verbosity an explicit type

* Compile with --quiet flag set will not output final stats

* Suppress size output if --quiet is specified

* Added -q shortcut to --quiet flag in compile command

* Compile recap is hidden also on a successful compile with default verbosity

* Made --quiet and --verbose mutually exclusive

* Output 'ctags' command line to stdout instead of stderr

* Do not output empty lines if the message is empty

* Added integration tests

* Use internal function to check for arguments exclusivity

Because it has a better error message than the cobra-provided one:

  Can't use the following flags together: --quiet, --verbose

Instead of:

  Error: if any flags in the group [quiet verbose] are set none of the others can be; [quiet verbose] were all set