Use internal function to check for arguments exclusivity
Because it has a better error message than the cobra-provided one:

  Can't use the following flags together: --quiet, --verbose

Instead of:

  Error: if any flags in the group [quiet verbose] are set none of the others can be; [quiet verbose] were all set