[skip changelog] Replace unbalanced backtick in comment
The comments in the Protocol Buffers source files are used in generated documentation. The generated documentation uses
Markdown.

Previously, a comment contained an unbalanced backtick. Since the backtick has syntactical significance in the Markdown
language, this caused the Markdown to be invalid, affecting parsing. This resulted in spurious failures of the link
check:

```
  ERROR: 103 dead links found in ./docs/rpc/commands.md !
  [✖] #cc.arduino.cli.commands.v1.DebugRequest → Status: 404
  [✖] #cc.arduino.cli.commands.v1.DebugResponse → Status: 404

[...]
```

The problem is resolved by replacing the stray backtick with a single quote, matching the existing companion quote
character. The alternative solution would be to replace the existing single quote character with a backtick. The switch
to single quote was chosen for consistency with another occurrence of this comment elsewhere in the code.